import type { Submission, Campaign, CreditRegistry, ValidationJob, Farmer, Profile, ValidatingAuthority, SatelliteCheck, PyrolysisProvider } from './types';

// ─── Campaigns (replaces Cooperatives) ───────────────────────

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign-1',
    company_id: 'company-1',
    company_name: 'Nestlé India',
    name: 'Punjab Wheat Insetting 2026',
    region: 'Ludhiana',
    state: 'Punjab',
    country: 'IN',
    crop_type: 'Wheat residue',
    price_per_tonne_usd: 65,
    min_tier: 'premium',
    max_tonnes: 500,
    collected_tonnes: 187,
    enrolled_farmers: 42,
    status: 'active',
    created_at: '2026-01-15T00:00:00Z',
    season: 'Rabi 2026',
  },
  {
    id: 'campaign-2',
    company_id: 'company-2',
    company_name: 'Microsoft',
    name: 'Rice Belt Carbon 2026',
    region: 'Amritsar',
    state: 'Punjab',
    country: 'IN',
    crop_type: 'Rice straw',
    price_per_tonne_usd: 60,
    min_tier: 'standard',
    max_tonnes: 1000,
    collected_tonnes: 412,
    enrolled_farmers: 78,
    status: 'active',
    created_at: '2026-02-01T00:00:00Z',
    season: 'Rabi 2026',
  },
  {
    id: 'campaign-3',
    company_id: 'company-3',
    company_name: 'Tata Sustainability',
    name: 'Haryana Green Initiative',
    region: 'Karnal',
    state: 'Haryana',
    country: 'IN',
    crop_type: 'Wheat residue',
    price_per_tonne_usd: 58,
    min_tier: 'standard',
    max_tonnes: 300,
    collected_tonnes: 89,
    enrolled_farmers: 23,
    status: 'active',
    created_at: '2026-03-01T00:00:00Z',
    season: 'Rabi 2026',
  },
];

// ─── Farmer profile ──────────────────────────────────────────

export const MOCK_FARMER_PROFILE: Profile = {
  id: 'farmer-1',
  role: 'farmer',
  phone: '+919876543210',
  name: 'Harpreet Singh',
  language: 'en',
  avatar_url: null,
  created_at: '2025-01-15T00:00:00Z',
};

export const MOCK_FARMER: Farmer = {
  id: 'farmer-1',
  field_gps: { type: 'Point', coordinates: [75.8402, 30.9120] },
  field_polygon: null,
  field_size_acres: 4.5,
  crop_type: 'Wheat / Rice',
  region: 'Ludhiana',
  state: 'Punjab',
  country: 'IN',
  cooperative_id: null,
  total_credits_earned: 18.4,
  total_payment_usd: 1104,
  total_payment_inr: 92736,
  seasons_active: 4,
  current_season: 'Rabi 2026',
  upi_id: 'harpreet@upi',
  mpesa_number: null,
};

// ─── Submissions ─────────────────────────────────────────────

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    created_at: '2025-12-18T09:30:00Z',
    biochar_photo_url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400',
    burial_photo_url: null,
    burial_gps: { type: 'Point', coordinates: [75.8402, 30.9120] },
    burial_depth_cm: 18,
    estimated_weight_kg: 45,
    quality_score: 5,
    carbon_tier: 'ultra',
    estimated_carbon_pct: 86,
    color_assessment: 'Jet black, matte finish with excellent porosity',
    improvement_tip: 'Maintaining excellent quality — keep current process.',
    is_valid_biochar: true,
    ai_confidence: 'high',
    credit_price_usd: 78,
    estimated_tonnes: 2.8,
    estimated_payment_inr: 18312,
    ai_verified: true,
    ai_verified_at: '2025-12-18T09:31:00Z',
    satellite_verified: true,
    satellite_verified_at: '2025-12-19T06:00:00Z',
    validator_verified: true,
    validator_verified_at: '2025-12-20T14:00:00Z',
    credit_hash: 'a3f8c2d1e5b7...',
    credit_minted: true,
    credit_minted_at: '2025-12-20T14:05:00Z',
    payment_sent: true,
    payment_sent_at: '2025-12-21T10:00:00Z',
    payment_amount_inr: 18312,
    payment_method: 'UPI',
    payment_reference: 'UPI/425871234567',
    status: 'paid',
  },
  {
    id: 'sub-2',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    created_at: '2026-01-05T11:15:00Z',
    biochar_photo_url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400',
    burial_photo_url: null,
    burial_gps: { type: 'Point', coordinates: [75.8410, 30.9125] },
    burial_depth_cm: 15,
    estimated_weight_kg: 38,
    quality_score: 4,
    carbon_tier: 'premium',
    estimated_carbon_pct: 72,
    color_assessment: 'Dark black with minor gray patches',
    improvement_tip: 'Slightly longer burn would push to ultra tier.',
    is_valid_biochar: true,
    ai_confidence: 'high',
    credit_price_usd: 62,
    estimated_tonnes: 2.1,
    estimated_payment_inr: 10962,
    ai_verified: true,
    ai_verified_at: '2026-01-05T11:16:00Z',
    satellite_verified: true,
    satellite_verified_at: '2026-01-06T06:00:00Z',
    validator_verified: true,
    validator_verified_at: '2026-01-07T10:00:00Z',
    credit_hash: 'b7e1d4c9f3a2...',
    credit_minted: true,
    credit_minted_at: '2026-01-07T10:05:00Z',
    payment_sent: true,
    payment_sent_at: '2026-01-08T09:00:00Z',
    payment_amount_inr: 10962,
    payment_method: 'UPI',
    payment_reference: 'UPI/425871234890',
    status: 'paid',
  },
  {
    id: 'sub-3',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    created_at: '2026-03-28T08:45:00Z',
    biochar_photo_url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400',
    burial_photo_url: null,
    burial_gps: { type: 'Point', coordinates: [75.8398, 30.9118] },
    burial_depth_cm: 20,
    estimated_weight_kg: 52,
    quality_score: 5,
    carbon_tier: 'ultra',
    estimated_carbon_pct: 84,
    color_assessment: 'Excellent matte black, highly porous structure',
    improvement_tip: 'No improvements needed – premium biochar quality.',
    is_valid_biochar: true,
    ai_confidence: 'high',
    credit_price_usd: 76,
    estimated_tonnes: 3.2,
    estimated_payment_inr: 20432,
    ai_verified: true,
    ai_verified_at: '2026-03-28T08:46:00Z',
    satellite_verified: true,
    satellite_verified_at: '2026-03-29T06:00:00Z',
    validator_verified: false,
    validator_verified_at: null,
    credit_hash: null,
    credit_minted: false,
    credit_minted_at: null,
    payment_sent: false,
    payment_sent_at: null,
    payment_amount_inr: null,
    payment_method: null,
    payment_reference: null,
    status: 'validator_pending',
  },
  {
    id: 'sub-4',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    created_at: '2026-04-02T07:20:00Z',
    biochar_photo_url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400',
    burial_photo_url: null,
    burial_gps: { type: 'Point', coordinates: [75.8405, 30.9122] },
    burial_depth_cm: 16,
    estimated_weight_kg: 40,
    quality_score: 3,
    carbon_tier: 'standard',
    estimated_carbon_pct: 58,
    color_assessment: 'Dark brown-black, moderate structure',
    improvement_tip: 'Burn a bit longer for darker, better biochar.',
    is_valid_biochar: true,
    ai_confidence: 'medium',
    credit_price_usd: 45,
    estimated_tonnes: 1.8,
    estimated_payment_inr: 6804,
    ai_verified: true,
    ai_verified_at: '2026-04-02T07:21:00Z',
    satellite_verified: false,
    satellite_verified_at: null,
    validator_verified: false,
    validator_verified_at: null,
    credit_hash: null,
    credit_minted: false,
    credit_minted_at: null,
    payment_sent: false,
    payment_sent_at: null,
    payment_amount_inr: null,
    payment_method: null,
    payment_reference: null,
    status: 'satellite_pending',
  },
];

// ─── Validation Jobs (campaign-assigned) ─────────────────────

export const MOCK_VALIDATION_JOBS: ValidationJob[] = [
  {
    id: 'job-1',
    submission_id: 'sub-3',
    farmer_id: 'farmer-1',
    validator_id: null,
    farm_gps: { type: 'Point', coordinates: [75.8398, 30.9118] },
    distance_km: 2.4,
    dispatched_at: '2026-03-29T06:05:00Z',
    accepted_at: null,
    arrived_at: null,
    completed_at: null,
    visit_photo_url: null,
    visit_gps: null,
    gps_match_distance_m: null,
    burial_depth_confirmed_cm: null,
    validator_notes: null,
    status: 'pending',
    payout_usd: null,
    farmer_rating: null,
    farmer: {
      ...MOCK_FARMER,
      profile: MOCK_FARMER_PROFILE,
    },
    submission: MOCK_SUBMISSIONS[2],
  },
  {
    id: 'job-2',
    submission_id: 'sub-x',
    farmer_id: 'farmer-2',
    validator_id: null,
    farm_gps: { type: 'Point', coordinates: [75.8650, 30.9200] },
    distance_km: 5.8,
    dispatched_at: '2026-03-30T07:00:00Z',
    accepted_at: null,
    arrived_at: null,
    completed_at: null,
    visit_photo_url: null,
    visit_gps: null,
    gps_match_distance_m: null,
    burial_depth_confirmed_cm: null,
    validator_notes: null,
    status: 'pending',
    payout_usd: null,
    farmer_rating: null,
  },
  {
    id: 'job-3',
    submission_id: 'sub-y',
    farmer_id: 'farmer-3',
    validator_id: null,
    farm_gps: { type: 'Point', coordinates: [75.8300, 30.8950] },
    distance_km: 8.1,
    dispatched_at: '2026-04-01T08:30:00Z',
    accepted_at: null,
    arrived_at: null,
    completed_at: null,
    visit_photo_url: null,
    visit_gps: null,
    gps_match_distance_m: null,
    burial_depth_confirmed_cm: null,
    validator_notes: null,
    status: 'pending',
    payout_usd: null,
    farmer_rating: null,
  },
];

// ─── Credits for company dashboard ───────────────────────────

export const MOCK_CREDITS: CreditRegistry[] = [
  {
    id: 'cr-1',
    credit_hash: 'a3f8c2d1e5b794f6a1c3d8e2f4b7a9e1c5d3f8a2b6e7d4c9f1a5b8d2e6c3f7',
    submission_id: 'sub-1',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    issued_at: '2025-12-20T14:05:00Z',
    tonnes: 2.8,
    quality_score: 5,
    carbon_tier: 'ultra',
    price_usd: 78,
    buyer_id: 'company-1',
    is_retired: false,
    retired_at: null,
    certificate_url: null,
  },
  {
    id: 'cr-2',
    credit_hash: 'b7e1d4c9f3a28d5e7b1c4f9a2d6e8b3c5f7a1d4e9b2c6f8a3d5e7b1c4f9a2d6',
    submission_id: 'sub-2',
    farmer_id: 'farmer-1',
    campaign_id: 'campaign-1',
    issued_at: '2026-01-07T10:05:00Z',
    tonnes: 2.1,
    quality_score: 4,
    carbon_tier: 'premium',
    price_usd: 62,
    buyer_id: 'company-1',
    is_retired: false,
    retired_at: null,
    certificate_url: null,
  },
];

// ─── Global CO₂ counter ─────────────────────────────────────

export const MOCK_GLOBAL_CO2 = 14280.6;

// ─── Validating Authorities ──────────────────────────────────
export const MOCK_AUTHORITIES: ValidatingAuthority[] = [
  {
    id: 'va-1',
    name: 'SGS India',
    accreditation: 'ISO 14065 / NABCB',
    region: 'National',
    specializations: ['Biochar', 'Soil Carbon'],
    partnered: true,
  },
  {
    id: 'va-2',
    name: 'Bureau Veritas',
    accreditation: 'VCS / Gold Standard',
    region: 'North India',
    specializations: ['Agricultural Residue'],
    partnered: false,
  },
  {
    id: 'va-3',
    name: 'Control Union',
    accreditation: 'CDM DOE',
    region: 'Punjab & Haryana',
    specializations: ['Forestry', 'Soil Carbon'],
    partnered: false,
  },
];

// ─── Satellite Checks ────────────────────────────────────────
export const MOCK_SATELLITE_CHECKS: SatelliteCheck[] = [
  {
    id: 'sat-1',
    farmer_id: 'farmer-1',
    coordinates: { type: 'Point', coordinates: [75.8402, 30.9120] },
    date: '2026-04-05T00:00:00Z',
    satellite_source: 'Sentinel-2',
    result: 'no_burn',
    confidence: 'high',
    image_url: null,
  },
  {
    id: 'sat-2',
    farmer_id: 'farmer-2',
    coordinates: { type: 'Point', coordinates: [75.8650, 30.9200] },
    date: '2026-04-04T00:00:00Z',
    satellite_source: 'Landsat 8',
    result: 'no_burn',
    confidence: 'high',
    image_url: null,
  },
  {
    id: 'sat-3',
    farmer_id: 'farmer-3',
    coordinates: { type: 'Point', coordinates: [75.8300, 30.8950] },
    date: '2026-04-03T00:00:00Z',
    satellite_source: 'Sentinel-2',
    result: 'burn_detected',
    confidence: 'medium',
    image_url: null,
  },
  {
    id: 'sat-4',
    farmer_id: 'farmer-4',
    coordinates: { type: 'Point', coordinates: [75.8800, 30.9400] },
    date: '2026-04-02T00:00:00Z',
    satellite_source: 'MODIS',
    result: 'no_burn',
    confidence: 'low',
    image_url: null,
  },
];

// ─── Pyrolysis Providers ─────────────────────────────────────
export const MOCK_PYROLYSIS_PROVIDERS: PyrolysisProvider[] = [
  {
    id: 'pyro-1',
    name: 'EarthFlame Solutions',
    type: 'vendor',
    description: 'Professional mobile pyrolysis units. We come to your farm.',
    region: 'Ludhiana District',
    cost_estimate: '₹1,500 / acre',
    rating: 4.8,
    contact_phone: '+919876543211',
  },
  {
    id: 'pyro-2',
    name: 'Punjab Green Farmers NGO',
    type: 'ngo',
    description: 'Free community kilns and training for marginal farmers.',
    region: 'Punjab',
    cost_estimate: 'Free',
    rating: 4.9,
    contact_phone: '+919876543212',
  },
  {
    id: 'pyro-3',
    name: 'Biochar Tech India',
    type: 'vendor',
    description: 'High-capacity continuous pyrolysis. Good for large estates.',
    region: 'North India',
    cost_estimate: '₹2,000 / acre',
    rating: 4.5,
    contact_phone: '+919876543213',
  },
  {
    id: 'pyro-4',
    name: 'DIY Kon Tiki Kiln',
    type: 'self',
    description: 'Dig a cone-shaped pit. Suitable for small scale biochar.',
    region: 'Anywhere',
    cost_estimate: 'Labor only',
    rating: null,
    contact_phone: '',
  },
];
